version: '3.2'
services:
  storybook:
    build:
      context: ./
      dockerfile: Dockerfile.storybook
  cypress:
    build:
      context: ./
      dockerfile: Dockerfile.cypress
    depends_on:
      - storybook
    environment:
      - CYPRESS_baseUrl=http://storybook
      - CYPRESS_browser=chrome
      - CYPRESS_screenshotsFolder=/results/screenshots
      - CYPRESS_videosFolder=/results/videos
    volumes: 
      - type: bind
        source: ./cypress/screenshots
        target: /results/screenshots
      - type: bind
        source: ./cypress/videos
        target: /results/videos