version: '3.2'
services:
  storybook:
    build:
      context: ./
      dockerfile: Dockerfile.storybook
  cypress:
    build:
      context: ./
      dockerfile: Dockerfile.cypress
    depends_on:
      - storybook
    environment:
      - CYPRESS_baseUrl=http://storybook